### ISSUE TITLE
Update Avatar

### ISSUE THREAD

**Issue by lw-cdm** [openbitdev/OpenBit-Wallet#27]
- In Send fund
- In Address book
- In Confirmation

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/tkH4isbmSTJWe4f
Validation passed in case display avatar on some screen : 



![Image](https://github.com/openbitdev/OpenBit-Wallet/assets/155931563/f04e6612-6f8e-470a-914e-5c495608010e)

- Displaying a fixed avatar for an account is currently not possible due to the keyring mechanism
-> Improve later
